import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/HomeClient.module.css'
import NavBarClients from '../components/NavBarClients'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div  className={styles.home_client_container}> 
      <NavBarClients/>
      {/*}
      <video muted autoPlay loop >
        <source src='../videos/videopeluqueria.mp4' type='video/mp4' >
      </video>*/}
      <video  autoPlay muted loop>
        <source src='../video/videopeluqueria.mp4' type='video/mp4' />
      </video>

       prueba

 
       
      </div>
 
    </div>
  )
}

export default Home
