import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import stylesHome from '../styles/HomeClient.module.css'
import NavBarClients from '../components/NavBarClients'
//import a from '../videos/videopeluqueria.mp4'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div  className={stylesHome.home_client_container}> 
        <NavBarClients/>
        {/*}
            <video  autoPlay muted loop>
          <source src='../videos/videopeluqueria.mp4'  type='video/mp4' />
        </video>
        */}
        <div className={stylesHome.input_container}>
          <h3>Reserve su turno</h3>
          <h5>busque todo tipo de rubros</h5>
          <div >
            <input></input>
            <p>buscar</p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
